languages:
  JavaScript: true
  Python: true

exclude_paths:
- "sitemetrics/runtests.py"
- "sitemetrics/tests.py"
- "sitemetrics/tests/*"
- "sitemetrics/migrations/*"
- "sitemetrics/south_migrations/*"
- "docs/*"
